\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Docker ubuntu

@copying
This manual is for, version version.

Copyright @copyright{} years copyright-owner.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title Document
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Docker ubuntu

This manual is for program, version version.
@end ifnottex

@menu
* Android build envrionment::
@c * Copying:: Your rights and freedoms.
@end menu

@node Android build envrionment
@chapter Android build envrionment

@itemize
@item
@b{Run docker ubuntu-12.04 hosted by ubuntu-16.04}
@end itemize

@example
@b{=> Docker install and run ubuntu 12.04 client}
  sudo apt-get install docker.io
  sudo docker pull ubuntu:12.04
  cat /etc/issue # check ubuntu version
  sudo docker run -v /absolute/path/to/host:/absolute/path/to/guest -i -t ubuntu:12.04 /bin/bash
    -> @b{Note:} -v 后面的两个参数指定host挂载到client的两个目录，需要替换成你自己的实际目录。
@end example

@example
@b{=> install basic ubuntu 12.04 android envrionment}
  Reference: @url{http://10.46.8.32/doc_htc/build_env/ubuntu-12.04.html}
  @b{Note:} Docker server 里面的 ubuntu 12.04 默认只有root用户，不过不要紧，这个root用户权限不高。
    按照手册安装12.04环境的时候，去掉sudo，安装之前先要 apt-get update 更新一下source。
@end example

@example
@b{=> install more ubuntu 12.04 android envrionment for docker}

  apt-get install bc

  cp -r /path/to/repo/ /home  # cp your repo to docker ubuntu 12.04
  apt-get install vim
  vim ~/.bashrc  # set repo path
  source ~/.bashrc

  export USER=$(whoami)
  echo $USER  # just for check
  ln -s /usr/bin/gcc /usr/bin/cc
@end example

@example
@b{=> commit your changes}

  root@@cd0fc1349818:/home# exit
  exit
  $ sudo docker commit -m "android build env" cd0fc1349818 ubuntu:12.04_android_env
   [sudo] password for zzy_i7:
   sha256:25afba688c5ef5ad391ee9d0c07a6b3407d8a5f58a1bdc3c5c778ecbda141f7e
  $ sudo docker images
   REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
   ubuntu              12.04_android_env   25afba688c5e        2 minutes ago       918.9 MB
   ubuntu              12.04_test          ccceeb237a25        59 minutes ago      103.6 MB
   <none>              <none>              2ae01793d0bd        About an hour ago   103.6 MB
   ubuntu              12.04               b384dd9703db        5 weeks ago         103.6 MB
  $ sudo docker run -v /media/zzy_i7/codebase:/home/codebase -i -t ubuntu:12.04_android_env /bin/bash

  Reference: @url{https://docs.docker.com/engine/reference/commandline/commit/}
@end example

@itemize
@item
@b{More docker commands}
@end itemize

@example
$ sudo docker images  # list images
[sudo] password for zzy_i7:
REPOSITORY          TAG                   IMAGE ID            CREATED             SIZE
ubuntu              12.04_android_env_1   7c27e497bd74        10 hours ago        918.9 MB
ubuntu              12.04                 b384dd9703db        6 weeks ago         103.6 MB

$ sudo docker save -o <save image to path> <image name>  # save image as tar file

$ sudo docker load -i <path to image tar file>           # load image from tar file

@b{Document: } @url{https://docs.docker.com/}
@end example

@bye
