\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle ft2-team docker images

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top ft2-team docker images

This manual is for program, version version.
@end ifnottex

@menu
* ubuntu_dev::
@c * Copying::  free time team
@end menu

@node ubuntu_dev
@chapter ubuntu_dev

@itemize
@item
@b{环境准备}
@end itemize
@ @ @ @ @ @ @ @ 下载环境: sudo docker pull ft2team/ubuntu_dev

@ @ @ @ @ @ @ @ 创建工作目录: mkdir work

@ @ @ @ @ @ @ @ Docker环境有两个用户，分别是root和user。

@ @ @ @ @ @ @ @ @b{Root用户:} root, password: <empty>

@ @ @ @ @ @ @ @ @b{普通用户:} user, password: 123

@itemize
@item
@b{用法介绍}
@end itemize
@ @ @ @ @ @ @ @ sudo docker run -v /absulote/path/to/work:/home/user/work -it ft2team/ubuntu_dev:latest su - user

@ @ @ @ @ @ @ @ 通过以上命令进入 docker 环境，其中 /absulote/path/to/work 指向 Host 工作目录

@bye
