\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Welcome

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Welcome

This manual is for program, version version.
@end ifnottex

@menu
* Welcome::
* Announcement::
* Communcation Platform::
@c * Copying::  free time team
@end menu

@node Welcome
@chapter Welcome
This is Free-time team welcome page

@node Announcement
@chapter Announcement

Announcement main page: @url{https://free-time-team.github.io/announcement.html, Announcement}

@node Communcation Platform
@chapter Communcation Platform

Communcation main page: @url{https://free-time-team.github.io/communication_platform.html, Communcation Platform}








@bye
