\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Ubuntu introduction

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Ubuntu introduction

This manual is for program, version version.
@end ifnottex

@menu
* Introduction::
* Install qemu::
@c * Copying::  free time team
@end menu

@node Introduction
@chapter Introduction

@itemize @bullet
@item
@b{Install ubuntu16.04}
@end itemize

@example
@b{Download ubuntu 16.04.1} @url{http://releases.ubuntu.com/16.04.1/ubuntu-16.04.1-desktop-amd64.iso, ubuntu16.04.1}
@b{Make USB boot} sudo dd if=ubuntu-16.04.1-desktop-amd64.iso of=/dev/sdc bs=8M;sync
@b{Note}
ubuntu-16.04.1-desktop-amd64.iso
/dev/sdc is your USB device
@end example

@itemize @bullet
@item
@b{Ubuntu16.04}
@end itemize

@example
Ubuntu16.04 (Long Term Support till 2021)
@end example

@itemize @bullet
@item
@b{Install basic tools}
@end itemize

@example
@b{simple edit}: sudo apt-get install gedit
@b{vim}: sudo apt-get install vim
@b{emacs}: sudo apt-get install emacs
@b{git}: sudo apt-get install git
@b{ctags}: sudo apt-get install ctags
@b{cscope}: sudo apt-get install cscope
@b{basic development}: sudo apt-get install build-essential
@b{ssh}: sudo apt-get install openssh-server openssh-client
@b{Atom}: https://atom.io/

@b{one more terminal}
sudo apt-get install mate-terminal
sudo apt-get install roxterm

@b{install sublime editor}
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer
@url{https://www.sublimetext.com/}
@url{http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2-3}

@b{install iptux}
sudo apt-get install iptux

@end example

@itemize
@item
@b{Install openjdk}
@end itemize

@example
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
@end example

@itemize
@item
@b{Install openjdk old version}
@end itemize

@example
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-7-jdk
@end example

@itemize
@item
@b{Change openjdk version}
@end itemize

@example
sudo update-alternatives --config java   # change java version
sudo update-alternatives --config javac  # change javac version
java -verson                             # check out current Java version
@end example

@itemize
@item
@b{Install chrome}
@end itemize

@example
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt-get update
sudo apt-get install google-chrome-stable
@end example

@itemize
@item
@b{Install Google Pinyin}
@end itemize

@example
@b{Command line}          sudo apt-get install fcitx-googlepinyin
@b{Setting}               System settings -> Language support -> Keyboard input method system -> change to fcitx.
@b{PC reset}              Log out/log in
@b{Setting}               Ubuntu Search -> Input -> Text entry setting
@b{Using Fcitx}           Click + -> Search "Google" -> find "Google Pinyin (Fcitx)"
@b{Change input methods}  Use "Ctrl+space" to switch between input methods
@end example

@itemize
@item
@b{Chrome plugin}
@end itemize

@example
@b{SwitchyOmega}
	Rule List URL: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
@end example

@itemize
@item
@b{vim config}

git clone @url{https://github.com/zzyjsjcom/vim.git, https://github.com/zzyjsjcom/vim.git}

@end itemize

@itemize
@item
@b{Openconnect}
@end itemize

@example
@b{install tools}
	sudo apt-get install openconnect
	sudo apt-get install vpnc
@b{get vpnc-script}
	curl -O https://free-time-team.github.io/bank/00resource/system/vpnc-script
	copy vpnc-script to /etc/vpnc/vpnc-script
@b{run}
	sudo openconnect --script /etc/vpnc/vpnc-script -u user_name https://vpn.example.com/
@b{reference}
	@url{http://www.infradead.org/openconnect/vpnc-script.html, http://www.infradead.org/openconnect/vpnc-script.html}
	@url{http://www.infradead.org/openconnect/, http://www.infradead.org/openconnect/}
@end example

@node Install qemu
@chapter Install qemu

@node install qemu for ubuntu16.04
@section install qemu for ubuntu16.04

@itemize
@item
@b{prepare dependency}

sudo apt-get install git ccache automake lzop bison gperf build-essential zip curl zlib1g-dev zlib1g-dev:i386 g++-multilib

sudo apt-get install python-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush

sudo apt-get install schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev ruby flex

sudo apt-get install libasound2 libasound2-dev flex libglib2.0-dev libtool libcap-dev

@item
@b{download qemu source code}

qemu-2.10.0 example => @url{https://download.qemu.org/, download qemu}

@item
@b{build & install}

tar -Jxf qemu-2.10.0.tar.xz

mkdir qemu-2.10.0/build/

cd qemu-2.10.0/build/

../configure @--@--prefix=/home/zzy/sdb/bin/qemu/qemu-2.10.0 @--@--target-list="arm-softmmu,aarch64-softmmu" @--@--enable-virtfs @--@--audio-drv-list=alsa

make -j8

make install
@end itemize



@bye
