\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Ubuntu basic

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Ubuntu basic

This manual is for program, version version.
@end ifnottex

@menu
* Introduction::
@c * Copying::  free time team
@end menu

@node Introduction
@chapter Introduction

@itemize @bullet
@item
@b{Install ubuntu16.04}
@end itemize

@example
@b{Download ubuntu 16.04.1} @url{http://releases.ubuntu.com/16.04.1/ubuntu-16.04.1-desktop-amd64.iso, ubuntu16.04.1}
@b{Make USB boot} sudo dd if=ubuntu-16.04.1-desktop-amd64.iso of=/dev/sdc bs=8M;sync
@b{Note}
ubuntu-16.04.1-desktop-amd64.iso
/dev/sdc is your USB device
@end example

@itemize @bullet
@item
@b{Ubuntu16.04}
@end itemize

@example
Ubuntu16.04 (Long Term Support till 2021)
@end example

@itemize @bullet
@item
@b{Install basic tools}
@end itemize

@example
@b{simple edit}: sudo apt-get install gedit
@b{vim}: sudo apt-get install vim
@b{emacs}: sudo apt-get install emacs
@b{git}: sudo apt-get install git
@b{ctags}: sudo apt-get install ctags
@b{cscope}: sudo apt-get install cscope
@b{basic development}: sudo apt-get install build-essential
@b{ssh}: sudo apt-get install openssh-server openssh-client
@b{Atom}: https://atom.io/

@b{one more terminal}
sudo apt-get install mate-terminal
sudo apt-get install roxterm

@b{install sublime editor}
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer
@url{https://www.sublimetext.com/}
@url{http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2-3}

@b{install iptux}
sudo apt-get install iptux

@end example

@itemize
@item
@b{Install openjdk}
@end itemize

@example
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
@end example

@itemize
@item
@b{Install openjdk old version}
@end itemize

@example
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-7-jdk
@end example

@itemize
@item
@b{Change openjdk version}
@end itemize

@example
sudo update-alternatives --config java   # change java version
sudo update-alternatives --config javac  # change javac version
java -verson                             # check out current Java version
@end example

@itemize
@item
@b{Install chrome}
@end itemize

@example
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt-get update
sudo apt-get install google-chrome-stable
@end example

@itemize
@item
@b{Install Google Pinyin}
@end itemize

@example
@b{Command line}          sudo apt-get install fcitx-googlepinyin
@b{Setting}               System settings -> Language support -> Keyboard input method system -> change to fcitx.
@b{PC reset}              Log out/log in
@b{Setting}               Ubuntu Search -> Input -> Text entry setting
@b{Using Fcitx}           Click + -> Search "Google" -> find "Google Pinyin (Fcitx)"
@b{Change input methods}  Use "Ctrl+space" to switch between input methods
@end example

@itemize
@item
@b{ubuntu upgrage}
@end itemize

@example
@b{point release upgrade}
sudo apt-get update
sudo apt-get upgrade
(or run sudo apt-get dist-upgrade)

@b{next release upgrade}
sudo apt-get update
sudo do-release-upgrade

@b{reference}
https://askubuntu.com/questions/804016/how-to-upgrade-from-16-04-lts-to-16-04-1-lts // ubuntu 小版本升级
https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-ubuntu-16-04-lts
https://help.ubuntu.com/lts/serverguide/installing-upgrading.html
https://askubuntu.com/questions/81585/what-is-dist-upgrade-and-why-does-it-upgrade-more-than-upgrade
http://manpages.ubuntu.com/manpages/zesty/en/man8/apt-get.8.html
http://lawrit.lawr.ucdavis.edu/it-help-center/how-to/upgrading-ubuntu-via-command-line
@end example

@c @itemize
@c @item
@c @b{Chrome plugin}
@c @end itemize

@c @example
@c @b{SwitchyOmega}
@c 	Rule List URL: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
@c @end example

@itemize
@item
@b{vim config}

git clone @url{git clone https://github.com/zzy-program/00_script.git}

@end itemize

@itemize
@item
@b{Openconnect}
@end itemize

@example
@b{install tools}
	sudo apt-get install openconnect
	sudo apt-get install vpnc
@b{get vpnc-script}
	curl -O https://free-time-team.github.io/bank/00resource/system/vpnc-script
	copy vpnc-script to /etc/vpnc/vpnc-script
@b{run}
	sudo openconnect --script /etc/vpnc/vpnc-script -u user_name https://vpn.example.com/
@b{reference}
	@url{http://www.infradead.org/openconnect/vpnc-script.html, http://www.infradead.org/openconnect/vpnc-script.html}
	@url{http://www.infradead.org/openconnect/, http://www.infradead.org/openconnect/}
@end example

@bye
