\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle About free time team

@copying
This manual is for Free-time team, version 1.0.

Copyright @copyright{} 2017-2027 years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top About free time team

This manual is for program, version version.
@end ifnottex

@menu
* Author::
* Free-time team introduction::
@c * Copying::  free time team
@end menu

@node Author
@chapter Author
todo

@node Free-time team introduction
@chapter Free-time team introduction
todo, will be updated








@bye
