\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Free-time team 简介

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} 2017-2018 years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Free-time team 简介

This manual is for program, version version.
@end ifnottex

@menu
* 作者::
* Free-time team 简介::
@c * Copying::  free time team
@end menu

@node 作者
@chapter 作者
version 1.0 周文嘉

@node Free-time team 简介
@chapter Free-time team 简介






@bye
