\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Android Environment

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Android Environment

This manual is for program, version version.
@end ifnottex

@menu
* Android local mirror::
* Codebase build::
@c * Copying::  free time team
@end menu

@node Android local mirror
@chapter Android local mirror

@itemize @bullet
@item
@b{Android local mirror} @url{android_local_mirror.html, creat android local mirror}
@end itemize

@node Codebase build
@chapter Codebase build

@itemize

@item
@b{Ubuntu-16.04} @url{ubuntu-16.04.html, codebase build for ubuntu-16.04}

@item
@b{Ubuntu-12.04} @url{ubuntu-12.04.html, codebase build for ubuntu-12.04}

@end itemize


@bye
