\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle makefile

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top makefile

This manual is for program, version version.
@end ifnottex

@menu
* makefile::
@c * Copying::  free time team
@end menu

@node makefile
@chapter makefile

@example
$@  扩展成当前规则的目的文件名
$<   扩展成依赖列表中的第 一个依赖文件
$^    扩展成整个依赖的列表

-include
The -include directive to include makefiles with no error for a nonexistent file comes

// for debug
make -j1 show_commands
make -j1 SHOW_COMMANDS=y

makefile
http://www.cnblogs.com/wanqieddy/archive/2011/09/21/2184257.html

http://stackoverflow.com/questions/1079832/how-can-i-configure-my-makefile-for-debug-and-release-builds
http://www.gnu.org/software/make/manual/make.html#Target%5F002dspecific
@end example








@bye
