\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle linux kernel maintainer YY 直播

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top linux kernel maintainer YY 直播

This manual is for program, version version.
@end ifnottex

@menu
* linux kernel maintainer YY 直播::
@c * Copying::  free time team
@end menu

@node linux kernel maintainer YY 直播
@chapter linux kernel maintainer YY 直播

@b{作者: zhi.a.wang@@linux.intel.com}

@b{整理: 周文嘉}


近期将会有 Intel 工程师， linux kernel GVT-g 作者， 以个人名义，在YY平台做一个直播。

和广大工程师一起做技术交流，内容会涵盖如何向 GVT-g 提交patch。
渴望对linux kenrel做贡献的同学，可以关注直播时间。

Ft2 team 将会把这些内容作为一个topic，整理、讨论，并且不定期在网站update。

@bye
