\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Computer vision

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Computer vision

This manual is for program, version version.
@end ifnottex

@menu
* Graphics plat::  first chapter
@c * Copying::  free time team
@end menu

@node Graphics plat
@chapter Graphics plat

@c todo http://www.linuxidc.com/Linux/2012-12/75255.htm

@example

computer vision

graphics_plat

apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl-gfx1.2-dev
git clone https://github.com/zzy-cv/graphics_plat.git graphics_plat
cd graphics_plat
make
./out/main

@end example

@bye
