\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Essential tools

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by 
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Essential tools

This manual is for program, version version.
@end ifnottex

@menu
* Introduction::  first chapter
@c * Copying::  free time team
@end menu

@node Introduction
@chapter Introduction

@example
source code

git clone https://github.com/prj-common/00tools.git

basic libs

libs/lib_base

character encode/decode

libs/lib_char_code

crc algorithm

libs/lib_crc

encryption/decryption algorithm

libs/lib_encrypt

hash algorithm

libs/lib_hash

zlib

libs/lib_zlib123
@end example

@bye