\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Linux basic

@copying
This manual is for linux basic Document, version 1.0

Copyright @copyright{} years free time team

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by 
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Linux basic

This manual is for linux basic, version1.0 
@end ifnottex

@menu
* Editor::
* Tools::
* Toolchain::
* Linux::
* Linux distribution::
* Linux init::
* Linux game::
@c * Copying::  free time team
@end menu

@node Editor
@chapter Editor

@example
Editor document: @url{linux_basic/editor.html, Editor}
Sed: @url{linux_basic/editor.html#sed, Editor->sed}
Vim: @url{linux_basic/editor.html#vim, Editor->vim}
LaTex: @url{linux_basic/editor.html#LaTex, Editor->LaTex}
texinfo: @url{linux_basic/editor.html#texinfo, Editor->texinfo}
markdown: @url{linux_basic/editor.html#markdown, Editor->markdown}
@end example

@node Tools
@chapter Tools

@example
Tools: @url{linux_basic/tools.html, tools}
@end example

@node Toolchain
@chapter Toolchain

@example
Toolchain: @url{linux_basic/toolchain.html, Toolchain}
@end example

@node Linux
@chapter Linux

@example
Linux: @url{linux_basic/linux.html, Linux}
@end example

@node Linux distribution
@chapter Linux distribution

@example
Linux Distribution: @url{linux_basic/linux_distro.html, Linux Distribution}
@end example

@node Linux init
@chapter Linux init

@example
Linux Init: @url{linux_basic/linux_init.html, Linux Init}
@end example

@node Linux game
@chapter Linux game

@example
Linux Game: @url{linux_basic/linux_game.html, Linux Game}
@end example

@bye






