\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle linux

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top linux

This manual is for program, version version.
@end ifnottex

@menu
* linux::
@c * Copying::  free time team
@end menu

@node linux
@chapter linux

==> @url{./resource/index.html, resource}

==> @url{./file_system/index.html, file system}

==> @url{./busybox/index.html, busybox}

==> @url{./daemon/index.html, daemon}

==> @url{./framebuffer/index.html, framebuffer}

==> @url{./gtk/index.html, gtk}

==> @url{./network_tools/index.html, network tools}

==> @url{./signal/index.html, signal}

==> @url{./syslinux/index.html, syslinux}





@bye
