\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle 汇编语言学习

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top 汇编语言学习

This manual is for program, version version.
@end ifnottex

@menu
* ARM 汇编语言学习环境搭建::
* ARM32 汇编学习::
* ARM64 汇编学习::
@c * Copying::  free time team
@end menu

@node ARM 汇编语言学习环境搭建
@chapter ARM 汇编语言学习环境搭建

这是一个基于 Docker + Ubuntu + qemu 的打包集成命令行环境。

@itemize
@item
@b{Docker安装}
@end itemize

@itemize
@item
@b{开发环境下载及简介}
@end itemize

@node ARM32 汇编学习
@chapter ARM32 汇编学习

@node ARM64 汇编学习
@chapter ARM64 汇编学习


@bye
