\input texinfo

@documentlanguage en
@documentencoding UTF-8

@settitle Communication Platform

@copying
This manual is for Document, version 1.0.

Copyright @copyright{} years free time team.

@quotation
Permission is granted to
@end quotation
@end copying

@titlepage
@title name-of-manual-when-printed en
@subtitle subtitle-if-any
@subtitle second-subtitle
@author author

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

Published by
@end titlepage

@c So the toc is printed at the start.
@contents

@ifnottex
@node Top
@top Communication Platform

This manual is for program, version version.
@end ifnottex

@menu
* Communication Platform::
@c * Copying::  free time team
@end menu

@node Communication Platform
@chapter Communication Platform
@b{QQ Group}
@example
free time group 479198558
@end example








@bye
